<a href="https://colab.research.google.com/github/JinsicLee/jinsic-lee/blob/main/221205_ch01_numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

골든 서클 이론
* Why? : 목적, 목표
* How? : 어떤 방식, 도구를 사용할 것이냐
* What? : 그래서 구체적으로 배우는게 뭐냐

인공지능 -> 인간의 지능을 흉내낸 컴퓨터 프로그램을 만드는 것
-> 컴퓨터 프로그램이다 / 많은 계산, 많은 데이터를 처리할 수 있어야함
-> 컴퓨터에게 최적화된 방식으로 데이터를 제공 (숫자나 규칙적으로 반복되는 것)
-> 컴퓨터가 이해하기 좋게 데이터를 다듬는 과정 (70%) : 전처리
-> 0, 1 ... (우리가 모르잖아요)
-> **반복되는 타입을 가진 나열된 데이터 (배열)**
=> Numpy


# 배열 (Array)
* 0개 이상의 데이터를 하나의 변수에 할당 : 리스트(list)

In [ ]:
a = []
a.append('a')
a

['a']

* 리스트 : 컴퓨터가 리스트를 싫어하는 이유
1. 길이가 가변적임 -> 메모리 문제
2. 들어가는 타입이 지멋대로임 -> int, str?
* 배열 (Array)
1. 길이가 고정적임 (원소의 갯수를 바꿀 수가 없음)
2. 타입이 고정적임 (모든 원소의 타입이 같은 자료형이여함)
-> 메모리 문제 (자리? 타입?)
=> 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음



In [ ]:
# 파이썬에는 배열을 처리하는 자체 내장 패키지 X
# !pip install numpy -> colab의 장점 : 웬만한 것 다 깔려있음
# import numpy
import numpy as np
# colab에서 tab 누르면 자동 완성
# colab 블록 실행 : ctrl + enter
# 블록을 실행하고 추가 블록 생성 : alt + enter

## 1차원 배열
* 축이 1개인 배열
* 리스트나 튜플처럼 한 줄로 이루어진 배열

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
arr = np.array([i for i in range(10)])
type(arr) # ndarray -> numpy를 통해서 생성된 배열

numpy.ndarray

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [ ]:
import random # 임의의 수

def average_python(n): 
    s = 0
    for i in range(n): # n번 반복문
        s += random.random() # 0~1 사이의 수 (+)
    # s = ??
    return s / n

In [ ]:
%time average_python(100000)
%timeit average_python(100000)

CPU times: user 14.9 ms, sys: 905 µs, total: 15.8 ms
Wall time: 16.6 ms
11.7 ms ± 957 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
def average_numpy(n):
    s = np.random.random(n)
    return s.mean() # 평균

In [ ]:
%time average_numpy(100000)
%timeit average_numpy(100000)

CPU times: user 3.1 ms, sys: 0 ns, total: 3.1 ms
Wall time: 2.13 ms
979 µs ± 27.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## 벡터화 연산 (vectorized operation)

In [ ]:
a = [1, 2, 3]
a

[1, 2, 3]

In [ ]:
# b = [2, 3, 4]
a + 1 # 리스트에서의 덧셈은 같은 리스트만 가능하고, 그것은 '연결'을 의미함

TypeError: ignored

In [ ]:
# c = [2, 4, 6]
a * 2 # 리스트에서의 곱셈은 정수만 가능하고, 해당 리스트를 n 배 반복하겠음

[1, 2, 3, 1, 2, 3]

* 배열 객체 (numpy.ndarray)는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리** = 벡터화 연산

In [ ]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # [i for i in range(10)]
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# 리스트 속에 있는 나열된 데이터를 모두 2배 처리
%%time
answer = []
for v in data:
    answer.append(v * 2)
answer

CPU times: user 24 µs, sys: 1 µs, total: 25 µs
Wall time: 38.4 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
# 리스트 컴프리헨션
%%time
answer2 = [x * 2 for x in data]
answer2

CPU times: user 16 µs, sys: 1e+03 ns, total: 17 µs
Wall time: 20 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
# 벡터화 연산
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
%time x * 2

CPU times: user 32 µs, sys: 6 µs, total: 38 µs
Wall time: 42 µs


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x / 2, x + 2, x ^ 2, x % 2, x ** 2

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11]),
 array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]))

* 벡터화 연산은 사칙연산 뿐만 아니라 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30]) # alt + shift + 위아래방향키 -> 복사
a, b

(array([1, 2, 3]), array([10, 20, 30]))

In [ ]:
2 * a + b # 산술 연산

array([12, 24, 36])

In [ ]:
a == 2, b > 10 # 비교 연산

(array([False,  True, False]), array([False,  True,  True]))

In [ ]:
# 논리연산
(a == 2) & (b > 10) # & : and 연산자 -> (같은 위치의 원소가) 둘 다 True인 경우

array([False,  True, False])

In [ ]:
(a == 2) | (b > 10) # | : or 연산자 => (같은 위치의) 원소 중 하나가 True인 경우

array([False,  True,  True])

## 2차원 배열
-> ndarray => n dimesion array => 다차원배열 자료구조를 지원
* 2차원 배열 : 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열 -> pandas
list of list / 리스트의 리스트 -> 2차원 배열
list of list of list / 리스트의 리스트의 리스트 -> 3차원 배열

In [ ]:
m = np.array([
    [0, 1, 2],
    [3, 4, 5]
]) # 2 x 3 행렬 / m x n : m 행의 갯수, n : 열의 개수
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 행의 갯수, 열의 개수
print(len(m)) # 행의 개수 - 가장 겉에 있는 리스트의 원소 개수
print(len(m[0])) # 열의 개수 - 가장 안에 있는 리스트의 원소 개수

2
3


## ⚓ 연습문제1
```
array([[10, 20, 30, 40],
       [50, 60, 70, 80]])
```

In [ ]:
d = [
 # 열, 열, 열, 열
  [10, 20, 30, 40], # 행
  [50, 60, 70, 80] # 행
]

In [ ]:
np.array(d)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [ ]:
d2 = [
  # 열, 열, 열, 열
  [1, 2, 3, 4], # 행
  [5, 6, 7, 8] # 행
]
np.array(d2) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열

In [ ]:
t = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
t # 2 x 3 x 4 배열

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [ ]:
# 깊이, 행, 열
len(t), len(t[0]), len(t[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기
* ndim, shape **속성** 사용
* ndim : 배열의 차원
* shape : 배열의 크기

In [ ]:
a.ndim, a.shape # 1차원 배열

(1, (3,))

In [ ]:
m.ndim, m.shape # 2차원 배열

(2, (2, 3))

In [ ]:
t.ndim, t.shape # 3차원 배열

(3, (2, 3, 4))

## 배열의 인덱싱

In [ ]:
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [ ]:
# a => 3을 가져오고 싶다
a[2]

3

In [ ]:
a[-3]

3

### 일차원 배열 인덱싱
* 리스트의 인덱싱과 같음

In [ ]:
a = np.array([0, 1, 2, 3, 4])
a[2], a[-1]

(2, 4)

### 다차원 배열 인덱싱
* 콤마(comma, `,`) 접근
* 콤마로 구분된 차원을 축(axis)이라고 함
* 그래프의 x축, y축

In [ ]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b[0, 0] # 첫번째 행의 첫번째 열

0

In [ ]:
b[0, 1] # 첫번째 행의 두번째 열

1

In [ ]:
b[-1, -1] # 마지막 행의 마지막 열

5

In [ ]:
b[0, 0] = 10
b[0, 0]
b

array([[10,  1,  2],
       [ 3,  4,  5]])

## 배열의 복사
* 얕은 복사 (Shallow Copy)
* 깊은 복사 (Deep Copy)

In [ ]:
1, '', 0.1 # 원시자료형
# 변수 - 연결관계 -> '객체'를 복사한다
a = [1, 2, 3]
a

[1, 2, 3]

In [ ]:
b = a # a라고 하는 값이 아니라 a 변수에 지정된 주소값
b

[1, 2, 3]

In [ ]:
a.append(4)
a

[1, 2, 3, 4]

In [ ]:
b # 얕은 복사

[1, 2, 3, 4]

In [ ]:
# 아예 새로 만들어줘서 연결 관계 끊기
c = ['a', 'b', 'c']
c

['a', 'b', 'c']

In [ ]:
d = " ".join(c).split()
# 주소를 옮기는게 아니라 아예 새로운 데이터를 메모리에 할당
d

['a', 'b', 'c']

In [ ]:
c.append('d')
d

['a', 'b', 'c']

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr2 = arr
arr2

array([1, 2, 3, 4])

In [ ]:
arr[0] = 10
arr2

array([10,  2,  3,  4])

In [ ]:
arr2.view() # 원본과 연결된 사본

array([10,  2,  3,  4])

In [ ]:
arr3 = arr.copy() # 속성은 () X, 메소드(함수) () O
arr3

array([100,   2,   3,   4])

In [ ]:
arr[0] = 100
arr3

array([100,   2,   3,   4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) # 배열의 데이터의 소유 여부
print(y.base)

None
[1 2 3 4 5]


## 배열의 슬라이싱

In [ ]:
x = [1, 2, 3, 4]
x[1:3] # a:b => a는 포함, b는 제외

[2, 3]

In [ ]:
x[-3:-1]

[2, 3]

In [ ]:
x[:-1]

[1, 2, 3]

* 다차원 배열의 원소 중 2개 이상의 (복수 개)를 접근할 때 일반적인 파이썬 슬라이싱과 콤마를 같이 사용

In [ ]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a[0, :] # 첫번째 행 전체

array([0, 1, 2, 3])

In [ ]:
a[:, 0] # 첫번째 열 전체

array([0, 4])

In [ ]:
a[1, 1:]

array([5, 6, 7])

In [ ]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

## ⚓ 연습문제2
```
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m
```
1. 값 7을 인덱싱
1. 값 14을 인덱싱
1. 배열 [6,7]을 슬라이싱
1. 배열 [7,12]을 슬라이싱
1. 배열 [[3,4],[8,9]]을 슬라이싱

In [ ]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#1 값 7을 인덱싱
m.shape
m[1,2],m[-2,-3],m[1,-3],m[-2,2]

(7, 7, 7, 7)

In [ ]:
#2 값 14를 인덱싱
m[2,-1], m[-1,4], m[-1,-1], m[2,4]

(14, 14, 14, 14)

In [ ]:
#3 배열 [6,7]을 슬라이싱
m
m[1,1:3]

array([6, 7])

In [ ]:
m[1, 1:3], m[-2, 1:3], m[1, -4:-2], m[-2, -4:-2]

(array([6, 7]), array([6, 7]), array([6, 7]), array([6, 7]))

In [ ]:
#4 배열 [7,12]을 슬라이싱
m[1:] # 2,3번째 행
m[1:,2]

array([ 7, 12])

In [ ]:
m[1:,2], m[-2:,2], m[-2:,-3], m[1:,-3]

(array([ 7, 12]), array([ 7, 12]), array([ 7, 12]), array([ 7, 12]))

In [ ]:
#5 배열 [[3,4],[8,9]]을 슬라이싱
m
m[:2]
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [ ]:
print(m[:2,3:])
print(m[:-1,3:])
print(m[:2,-2:])
print(m[:-1,-2:])

[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


## 배열 인덱싱 (배열을 넣어서 인덱싱하겠다)
* arr[...] => 정수형의 값. 슬라이싱 (:) 범위...
* 대괄호(bracket,[]) 안에 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 넣어서 특정 조건을 만족시키는 값만 조회
* 1) 불(Bool)리언 값으로 되어 있는 배열
* 2) 정수 인덱스 배열

### 불리언 배열 인덱싱
- 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같을 때
- 벡터화 연산 -> 비교, 논리연산

In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) # 배열 -> 짝수 원소만 골라내고 싶다
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [ ]:
# 벡터화 연산 -> 논리 연산, 비교 연산
a % 2 # 2의 배수라는 것은 (짝수라는 것은) 나머지가 0일 때
a % 2 == 0 # 짝수의 조건식

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a % 2 == 0] # 조건문으로 계산해서 (벡터화 연산) 원래 배열에 인덱스에 넣어주면, 필터링이 된다

array([0, 2, 4, 6, 8])

In [ ]:
a[a % 3 == 0]

array([0, 3, 6, 9])

In [ ]:
a[a % 3 != 0]

array([1, 2, 4, 5, 7, 8])

### 정수 배열 인덱싱
* 원래 배열의 인덱스 -> 정수값의 라벨링 (0~)
* 특정 정수들의 인덱스 배열을 넣으면, 해당 정수에 대응하는 값을 찾아서 표현해줌

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) * 11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [ ]:
idx2 = np.array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])
a[idx2]

array([11, 11, 11, 11, 22, 22, 22, 22, 33, 33, 33, 33])

## 다차원 배열에서의 배열 인덱싱

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [ ]:
a[[2, 0, 1], :] # 2번째, 0번째, 1번째

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## ⚓ 연습문제3
```
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
```
1. 3의 배수 찾기
1. 4로 나누면 1이 남는 수 찾기
1. 3으로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기


In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# 1 : 3의 배수 찾기
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# 2 : 4로 나누면 1이 남는 수 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [ ]:
# 3 : 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
x[(x % 3 == 0) & (x % 4 == 1)], x[(x % 3 == 0) | (x % 4 == 1)]

(array([9]), array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18]))

## 배열 검색

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

In [ ]:
x = np.where(arr == 4) # np.where(condition) -> 조건을 만족시키는 인덱스를 리턴
x

(array([3, 5, 6]),)

In [ ]:
arr[x]

array([4, 4, 4])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr % 2 == 0)

x

(array([1, 3, 5, 7]),)

In [ ]:
arr[x]

array([2, 4, 6, 8])